### ISSUE TITLE
Like/dislike buttons don't turn blue

### ISSUE THREAD

**Issue by Jamesgsburns** [DamienDavisNeff/RedSubscribeButton#21]
Just like my last issue, I'm using chrome and the present version of the extension.
You can see the like and dislike buttons not turning blue for yourself, no need for a screenshot.

**Comment by DamienDavisNeff** [comment]
Does it stay the default color, or does it change to a different color? @Jamesgsburns

**Comment by Jamesgsburns** [comment]
I said "look for yourself"... It is the default black/white color depending on the themes...

**Comment by DamienDavisNeff** [comment]
I asked for this information as I was not home to "look for myself"

With that being said, there is a workaround available

1. Open settings menu
![image](https://user-images.githubusercontent.com/105996288/229597972-0484ea7a-13df-4c6f-a59d-8f8041269993.png)
2. Reset to default settings
![image](https://user-images.githubusercontent.com/105996288/229598062-6f7c618e-29f8-4515-a831-1d454b7aab27.png)
3. Reapply any custom settings you had

This issue is caused by a miscommunication between the settings being saved, and being displayed. This also causes the default color for the like button to be displayed as black, when you turn it off and on again.

**Comment by DamienDavisNeff** [comment]
This was actually a very quick fix, and was just caused by a typo in the `apply_settings.js` file. The hex value of the color for the like button was not properly being loaded, as the `#` was forgotten.

`"like-color": "50a0f0"` 👉 `"like-color": "#50a0f0"`

**Comment by DamienDavisNeff** [comment]
This update has been pushed to the Chrome Webstore and will be available in the next few days.

Please note, if you (@Jamesgsburns) haven't done so already, you may still be required to reset your settings to fix the issue, as the bugged hex code is stored in the extensions storage.

**Comment by Jamesgsburns** [comment]
I never click on the extensions when available on the top of the screen and didn't know you can change the color settings until you showed the images. Why exactly do you have that option to change the colors? It makes sense to put in the "boxy buttons" option but the rest of the options don't.
